---
title: "R Notebook"
output: html_notebook
---

# 02 24 2020

## Loading the data

```{r}
library(mosaic)
```


```{r}
DelPrete <- read_excel("Delprete.xlsx")

# Changning data into a data frame

DelPrete <- as.data.frame(DelPrete)

View(Delprete)

library(mosaic)

```

```{r}
DelPrete <- Delprete
DelPreteTW <- subset(DelPreteTW, Collection_number !=1)
DelPreteTW <- subset(DelPreteTW, Collection_number !=2)
DelPreteTW <- subset(DelPreteTW, Collection_number !=3)
DelPreteTW <- subset(DelPreteTW, Ethnicity !="B")
```


## Descriptives

```{r}
favstats(DelPreteTW$Index_AP_inlet)
favstats(DelPreteTW$Index_bispinous)
favstats(DelPreteTW$Index_TD_outlet)
```

# Ap Inlet
```{r}
plot(DelPreteTW$Index_AP_inlet, DelPreteTW$GM, xlab = "AP Inlet", ylab="Geometric Mean", main = "AP Inlet vs. Geometric Mean")
plot(DelPreteTW$Index_AP_inlet, DelPreteTW$femur_head_adjusted_1.715, xlab = "AP Inlet", ylab="Femur Head Adjusted", main ="AP Inlet vs. Femur Head")

cor.test(DelPreteTW$Index_AP_inlet, DelPreteTW$GM)
cor.test(DelPreteTW$Index_AP_inlet, DelPreteTW$femur_head_adjusted_1.715)
```
# TD Outlet
```{r}
plot(DelPreteTW$Index_TD_outlet, DelPreteTW$GM, xlab = "TD Outlet", ylab="Geometric Mean", main = "TD Outlet vs. Geometric Mean")
plot(DelPreteTW$Index_TD_outlet, DelPreteTW$femur_head_adjusted_1.715, xlab = "TD Outlet", ylab="Femur Head Adjusted", main ="TD Outlet vs. Femur Head")

cor.test(DelPreteTW$Index_TD_outlet, DelPreteTW$GM)
cor.test(DelPreteTW$Index_TD_outlet, DelPreteTW$femur_head_adjusted_1.715)

```

# Bispinous
```{r}
plot(DelPreteTW$Index_bispinous, DelPreteTW$GM, xlab = "Bispinous", ylab="Geometric Mean", main = "Bispsinous vs. Geometric Mean")
plot(DelPreteTW$Index_bispinous, DelPreteTW$femur_head_adjusted_1.715, xlab = "Bispinous", ylab="Femur Head Adjusted", main ="Bispinous vs. Femur Head")

cor.test(DelPreteTW$Index_bispinous, DelPreteTW$GM)
cor.test(DelPreteTW$Index_bispinous, DelPreteTW$femur_head_adjusted_1.715)
```

# Pelvic Breadth
```{r}
plot(DelPreteTW$Index_pelvic_breadth, DelPreteTW$GM, xlab = "Pelvic Breadth", ylab="Geometric Mean", main = "Pelvic Breadth vs. Geometric Mean")
plot(DelPreteTW$Index_pelvic_breadth, DelPreteTW$femur_head_adjusted_1.715, xlab = "Pelvic Breadth", ylab="Femur Head Adjusted", main ="Pelvic Breadth vs. Femur Head")

cor.test(DelPreteTW$Index_pelvic_breadth, DelPreteTW$GM)
cor.test(DelPreteTW$Index_pelvic_breadth, DelPreteTW$femur_head_adjusted_1.715)
```

# AP Outlet
```{r}
plot(DelPreteTW$Index_AP_outlet, DelPreteTW$GM, xlab = "AP Outlet", ylab="Geometric Mean", main = "AP Outlet vs. Geometric Mean")
plot(DelPreteTW$Index_AP_outlet, DelPreteTW$femur_head_adjusted_1.715, xlab = "AP Outlet", ylab="Femur Head Adjusted", main ="AP Outlet vs. Femur Head")


cor.test(DelPreteTW$Index_AP_outlet, DelPreteTW$GM)
cor.test(DelPreteTW$Index_AP_outlet, DelPreteTW$femur_head_adjusted_1.715)
```
