---
title: "scratch_notebook_delprete"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r}
DelPrete <- read_excel("Delprete.xlsx")
DelPreteTB <- subset(DelPrete, Collection_number !=1)
DelPreteTB <- subset(DelPrete, Collection_number !=2)
DelPreteTB <- subset(DelPrete, Collection_number !=3)
DelPreteTB <- subset(DelPreteTB, Ethnicity !="W")

View(DelPreteTB)
```

```{r}
install.packages("mosaic")
```
```{r}
library(mosaic)
```

# Descriptives
```{r}
favstats(DelPrete$Index_AP_inlet)
favstats(DelPrete$Index_bispinous)
favstats(DelPrete$Index_TD_outlet)
```

## Scatterplot of Index Values vs Femur Head Adjusted and GM
```{r}
plot(DelPrete$Index_AP_inlet, DelPrete$femur_head_adjusted_1.715, xlab="AP Inlet", ylab="Femur Head Adjusted", main="AP Inlet vs. Femur Head (TW)")
plot(DelPrete$Index_AP_inlet, DelPrete$GM, xlab="AP Inlet", ylab="Geometric Mean", main="AP Inlet vs. GM (TW)")

plot(DelPrete$Index_bispinous, DelPrete$femur_head_adjusted_1.715, xlab="Bispinous", ylab ="Femur Head Adjusted", main="Bispinous vs. Femur Head (TW)")
plot(DelPrete$Index_bispinous, DelPrete$GM, xlab="Bispinous", ylab="Geometric Mean", main="Bispinous vs. GM (TW)")

plot(DelPrete$Index_TD_outlet, DelPrete$femur_head_adjusted_1.715, xlab="TD Outlet", ylab="Femur Head Adjusted", main="TD Outlet vs. Femur Head (TW)")
plot(DelPrete$Index_TD_outlet, DelPrete$GM, xlab="TD Outlet", ylab="Geometric Mean", main="TD Outlet vs. GM (TW)")

plot(DelPrete$Index_pelvic_breadth, DelPrete$GM, xlab ="Index Pelvic Breadth", ylab="Geometric Mean", main ="Pelvic Breadth vs. GM (TB)")
plot(DelPrete$Index_pelvic_breadth, DelPrete$femur_head_adjusted_1.715, xlab ="Index Pelvic Breadth", ylab="Femur Head Adjusted", main ="Pelvic Breadth vs. Femur Head (TB)")

plot(DelPrete$Index_AP_outlet, DelPrete$GM, xlab ="Index AP Outlet", ylab="Geometric Mean", main="AP Outlet vs. GM")
plot(DelPreteTB$Index_AP_outlet, DelPreteTB$femur_head_adjusted_1.715, xlab ="Index AP Outlet", ylab="Femur Head Adjusted", main = "AP Outlet vs. Femur Head (TB)")

plot(DelPreteTB$Index_AP_inlet, DelPreteTB$femur_head_adjusted_1.715, xlab="AP Inlet", ylab="Femur Head Adjusted")
plot(DelPreteTB$Index_AP_inlet, DelPreteTB$GM, xlab="AP Inlet", ylab="Geometric Mean")

plot(DelPreteTB$Index_bispinous, DelPreteTB$femur_head_adjusted_1.715, xlab="Bispinous", ylab ="Femur Head Adjusted", main="Bispinous vs. Femur Head (TB)")
plot(DelPreteTB$Index_bispinous, DelPreteTB$GM, xlab="Bispinous", ylab="Geometric Mean", main="Bispinous vs. Geometric Mean (TB)")

plot(DelPreteTB$Index_TD_outlet, DelPreteTB$femur_head_adjusted_1.715, xlab="TD Outlet", ylab="Femur Head Adjusted", main="TD Outlet vs. Femur Head (TB)")
plot(DelPreteTB$Index_TD_outlet, DelPreteTB$GM, xlab="TD Outlet", ylab="Geometric Mean", main="TD Outlet vs. Femur Head (TB)")

plot(DelPreteTB$Index_pelvic_breadth, DelPreteTB$GM, xlab ="Index Pelvic Breadth", ylab="Geometric Mean", main ="Pelvic Breadth vs. GM (TB)")
plot(DelPreteTB$Index_pelvic_breadth, DelPreteTB$femur_head_adjusted_1.715, xlab ="Index Pelvic Breadth", ylab="Femur Head Adjusted", main ="Pelvic Breadth vs. Femur Head (TB)")

plot(DelPreteTB$Index_AP_outlet, DelPreteTB$GM, xlab ="Index AP Outlet", ylab="Geometric Mean", main="AP Outlet vs. GM (TB)")
plot(DelPreteTB$Index_AP_outlet, DelPreteTB$femur_head_adjusted_1.715, xlab ="Index AP Outlet", ylab="Femur Head Adjusted", main = "AP Outlet vs. Femur Head (TB)")
```

## Scatterplot of Index Values vs Age
```{r}
plot(DelPrete$Index_AP_inlet, DelPrete$Age)
plot(DelPrete$Index_bispinous, DelPrete$Age)
plot(DelPrete$Index_TD_outlet, DelPrete$Age)

```
```{r}
cor(DelPrete$Index_AP_inlet, DelPrete$three_groups)
cor(DelPrete$Index_bispinous, DelPrete$three_groups)
cor(DelPrete$Index_TD_outlet, DelPrete$three_groups)
cor(DelPrete$Index_bispinous, DelPrete$Index_TD_outlet)
plot(DelPrete$Index_bispinous, DelPrete$Index_TD_outlet)

```


## ln of GM
```{r}
Delprete$lnGM <- log(Delprete$GM)
Delprete$lnGM
```


## Pelvic Breath
```{r}
plot(DelPrete$Index_pelvic_breadth, DelPrete$GM, xlab ="Index Pelvic Breadth", ylab="Geometric Mean", main ="Pelvic Breadth vs. GM")
plot(DelPrete$Index_pelvic_breadth, DelPrete$femur_head_adjusted_1.715, xlab ="Index Pelvic Breadth", ylab="Femur Head Adjusted", main ="Pelvic Breadth vs. Femur Head")

cor(DelPrete$Index_pelvic_breadth, DelPrete$femur_head_adjusted_1.715)
cor(DelPrete$Index_pelvic_breadth, DelPrete$GM)

```
## AP Outlet
```{r}
plot(DelPrete$Index_AP_outlet, DelPrete$GM, xlab ="Index AP Outlet", ylab="Geometric Mean", main="AP Outlet vs. GM")
plot(DelPrete$Index_AP_outlet, DelPrete$femur_head_adjusted_1.715, xlab ="Index AP Outlet", ylab="Femur Head Adjusted", main = "AP Outlet vs. Femur Head")

cor(DelPrete$Index_AP_outlet, DelPrete$femur_head_adjusted_1.715)
cor(DelPrete$Index_AP_outlet, DelPrete$GM)
```

